describe('Registro Prestashop', function() {
    it('Ingresar formulario pagina de registro', function() {
        cy.visit('http://ec2-18-222-141-129.us-east-2.compute.amazonaws.com:8080/es/')
        cy.contains('Iniciar sesión').click()
        cy.get('.login-form').find('input[name="email"]').click().type("prueba@prueba.com")
        cy.get('.login-form').find('input[name="password"]').click().type("12345678")
        cy.get('.login-form').contains('Iniciar sesión').click()
        cy.contains('Añadir primera dirección').click()
        cy.get('.address-form').find('input[name="alias"]').click().type("Dirección 1")
        cy.get('.address-form').find('input[name="company"]').click().type("Pruebas Automaticas SAS")
        cy.get('.address-form').find('input[name="vat_number"]').click().type("19")
        cy.get('.address-form').find('input[name="address1"]').click().type("Celle falsa 123")
        cy.get('.address-form').find('input[name="address2"]').click().type("Calle anonima 456")
        cy.get('.address-form').find('input[name="postcode"]').click().type("110010")
        cy.get('.address-form').find('input[name="city"]').click().type("Bogota")
        cy.get('.address-form').find('select[name="id_country"]').select("Colombia")
        cy.get('.address-form').find('input[name="phone"]').click().type("7450000")
        cy.get('.form-footer').find('button[type="submit"]').click({ force: true })
        cy.contains('¡Dirección añadida correctamente!')
        cy.get('.address-footer').contains('Eliminar').click()
        cy.contains('¡Dirección eliminada correctamente!')
        cy.contains('Cerrar sesión').click()
        cy.contains('Iniciar sesión con su cuenta')
    })
})